server {
    listen 8081;
    server_name __SERVER_NAME__;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 8443 ssl;
    server_name __SERVER_NAME__;

    ssl_certificate /etc/ssl/certs/edu-resource-monitor.crt;
    ssl_certificate_key /etc/ssl/private/edu-resource-monitor.key;

    access_log /var/log/nginx/edu-resource-monitor.access.log;
    error_log /var/log/nginx/edu-resource-monitor.error.log;

    location / {
        proxy_pass http://127.0.0.1:__APP_PORT__;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
